### ISSUE TITLE
1.2.1 Windows versions without installer

### ISSUE THREAD

**Issue by jguille2** [bromagosa/Snap4Arduino#105]
Official downloads for 1.2.1 version in [win32](http://snap4arduino.org/downloads/1.2.1/Snap4Arduino_desktop-win-32_1.2.1.zip) and [win64](http://snap4arduino.org/downloads/1.2.1/Snap4Arduino_desktop-win-64_1.2.1.zip) haven't installer exe file (like in older versions).

**Comment by bromagosa** [comment]
Ouch!

One shouldn't publish anything before leaving on vacation... I'll upload new installers this morning! :)

**Comment by bromagosa** [comment]
It's done and uploaded now! Sorry about the delay!
