### ISSUE TITLE
Transpilation not working in web-based versions

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/Snap4Arduino#107]
Neither Chromium, ChromeOS or Linino (ws) versions support transpilation ATM.

**Comment by jguille2** [comment]
Hi @bromagosa,

Transpilation is now (master branch, not released) working in Chromium version.

I we disconntinue support for chromeOs and linino, we can close this issue.

**Comment by jguille2** [comment]
Now, transpilation is working in desktop and chromium released versions.
I think we can close this issue.
