### ISSUE TITLE
Leap Motion on local version

### ISSUE THREAD

**Issue by fzsigmond** [bromagosa/Snap4Arduino#108]
We are trying to use Leap Motion to control a robotic arm on Snap4Arduino. Back in January I could make it work, but now, when I click on any block from the Leap Motion library I get the message below:

Inside: Type Error
Cannot read property ‘frame’ of undefined

We are using Arduino IDE 1.6.9 and Snap4Arduino 1.2.1 (Mac OSX). StandardFirmata is loaded and the board connects fine.
Everything works well on the browser version, we get LeapMotion and Arduino working. The issue only happens when we use the local version of Snap4Arduino.

**Comment by jguille2** [comment]
Hi @fzsigmond,
I have not any experience with LeapMotion, but from code I see:
  - Your error "cannot read property 'frame' of undefined" is normal before executing the _Leap_ block
![leap](https://cloud.githubusercontent.com/assets/2926315/21205312/d4c72510-c25b-11e6-9594-581bdb257b16.png)
  - _Leap_ block creates _window.controler_ object. Then, all the other blocs use _frame_ like a property of this _window.controler_

So, be sure tu execute _Leap_ block first. If you already did this, the problem is in this execution.

**Comment by fzsigmond** [comment]
Thank you for your prompt response! The issue is weird, because the exact same code that runs on the s4a browser version, does not run on the downloaded s4a version.By the error message, could that be that there is a missing piece of code that handles the "leap" block on the downloaded s4a? 
Best, 
Fabio



Sent from my Samsung device

-------- Original message --------

**Comment by jguille2** [comment]
One question, are your PC connected to Internet?
_Leap_ block use an online library at "crossorigin.me/http://js.leapmotion.com/leap-0.6.4.min.js"
![http_leap](https://cloud.githubusercontent.com/assets/2926315/21206465/7dd691c6-c262-11e6-8597-8da42ca5e0bd.png)
Test this _http reporter_. If this report nothing... this is the problem.

If you need work without Internet connection, you can download this _js_ and change _http reporter_ URL to "http://localhost/..."

Joan

**Comment by fzsigmond** [comment]
Hi Joan,

My computer is connected to the internet.
I get this message when I tried the reporter:

Origin: header is required



Could you walk me through the steps in order to download the code and change the appropriated code?

Thank you,

Fabio

**Comment by jguille2** [comment]
Oh, I see...
This '_header is required_' apears in Snap4Arduino_local (Nor web version and nor Snap! online/offline).

I have no time now... but tomorrow we'll see
Joan

**Comment by fzsigmond** [comment]
Exactly! 
Thanks for your time, send me the instructions when possible.

Fabio

**Comment by jguille2** [comment]
Hi fabio @fzsigmond !
Test this:
Edit _Leap_block and change this URL 'crossorigin.me/http://js.leapmotion.com/leap-0.6.4.min.js' for this other 'js.leapmotion.com/leap-0.6.4.min.js'

I think, this will run ok.
Note: For the other versions (online, snaps...) you will need the original (with the crossorigin.me proxy).

Joan

**Comment by fzsigmond** [comment]
Thanks Joan, that worked!
Is there a way to adjust this also on the Leap Motion file that installs when you select the install library from within the Snap4Arduino local version?

Best,

Fabio

**Comment by bromagosa** [comment]
Hi @fzsigmond!

Please send me the modified library and I'll make sure to include that one locally :)

**Comment by fzsigmond** [comment]
Hi Bernat,

Please see the modified file on the  attachment .

Best,

Fabio

**Comment by bromagosa** [comment]
Hi Fabio, I'm afraid you can't send attachments to Github issues by email, you'll need to retry by using the Github UI.

**Comment by fzsigmond** [comment]
[leap.xml.zip](https://github.com/bromagosa/Snap4Arduino/files/666428/leap.xml.zip)

**Comment by bromagosa** [comment]
Thanks! It's already done, and will be available in 1.2.2, which I'll be publishing tomorrow :)
