### ISSUE TITLE
Arduino and WiFi main board connection

### ISSUE THREAD

**Issue by aidiken** [bromagosa/Snap4Arduino#110]
There is no way in Arduino, http://snap.berkeley.edu/snapsource/snap.html and WiFi motherboard connection  ?

**Comment by bromagosa** [comment]
I'm not sure I understand the question. If you're asking whether Snap4Arduino can connect to Arduino boards via WiFi, the answer is yes, by using an ESP8266 module and the Network Serial Port functionality available under the settings menu.

It is an undocumented feature though, we really need to do a better job at documentation. Actually, let me add this to my ToDo for next week. I'll start populating the Wiki with examples and howtos.

**Comment by aidiken** [comment]
Thank you very much

**Comment by aidiken** [comment]
@bromagosa Thank you very much
