### ISSUE TITLE
Using a servo motor

### ISSUE THREAD

**Issue by mrlsm40** [bromagosa/Snap4Arduino#117]
My greetings.
I´m using a ultrasonic sensor conected at a servo motor and I want the first one take a turn of some degrees. How can I do this programmimng in snap4arduino??
Why I did not find "MOTOR ___ DEGREE ___"  block as in S4A?? Is there any block that replace it??
Why I did not find "SET PWM PIN ___ TO ___ " block in my snap4arduino version??
I did the updated firmata as explained in your blog but it does not worked (probably because I did not know how to do). The tools did not appear in snap4arduino.
Sorry for to many questions but I need and want to learn all about this software.
Thanks again
Márcio Rocha Lima (Brazil)

**Comment by jguille2** [comment]
Hi,
  - servoMotor: Use block 'set servo PIN to VALUE' where VALUE is the angle (0-180)
  - pwm: Use the block 'set pin PIN to value VALUE' where VALUE is 0-255.
  - ultrasonic. You can't do it with StandardFirmata. Take a look ara [sa5firmata](https://github.com/jguille2/SA5/blob/master/firmata/SA5Firmata.md)

Joan
