### ISSUE TITLE
Costumes and Backgrounds images

### ISSUE THREAD

**Issue by nmrds** [bromagosa/Snap4Arduino#126]
Thanks for the improvements in this last version.

I notice that the Costumes and the Backgrounds now open a window that shows the images, which is a good feature. Is the import button still beening in developed? because mine doesn't work

I extracted the Snap4Arduino.exe file and notice that you added new images to the  Costumes and Backgrounds folder, but this new images aren't visible inside the application. Can you fix it?

And can you give me some tips how can I build the Snap4Arduino.exe file in windows.

Regards

**Comment by bromagosa** [comment]
You're right, thanks for noticing! I just realized I forgot to sync the costumes loader. I've just done that right now.

As for building Snap4Arduino under Windows, I can only suggest that you either read the documentation of [nwjs.io](http://docs.nwjs.io/en/latest/) and do it manually, use something like cygwin (or powershell, shouldn't that work?), or install a GNU/Linux in a virtual machine. Or just wipe Windows altogether and install a secure, backdoor-free, people-owned, and non-surveilled system! :stuck_out_tongue_winking_eye:
