### ISSUE TITLE
File permissions for cordova

### ISSUE THREAD

**Issue by sudarshan395** [bromagosa/Snap4Arduino#142]
Need help to add file permissions for cordova to import and export blocks . How to add file permissions to cordova ? We tried but we are not able to find the directory where we can add the plugin
We used this instruction 
cordova plugin add cordova-plugin-file

It says this is not a cordova based project . How to find that directory , we are only getting Snap4Arduino.apk.

**Comment by bromagosa** [comment]
Yep, I was planning to work on this soon.

Please bear in mind that the Cordova version is not published yet because it's unfinished. Many things are missing and it's not recommended for anybody to use it yet.

The pre-alpha will hopefully come out by the end of April.

**Comment by bromagosa** [comment]
This is implemented now :)
