### ISSUE TITLE
Get URL from shared project

### ISSUE THREAD

**Issue by jferran6** [bromagosa/Snap4Arduino#143]
It would be useful to have a quick method to get the URL of a shared project. Perhaps directly from the list of projects ...

Josep

**Comment by bromagosa** [comment]
Fixed in the dev version:

![out](https://cloud.githubusercontent.com/assets/1016697/23949387/4fc5263c-0987-11e7-80a9-e8fbb8aaa630.gif)

**Comment by jferran6** [comment]
Great !!
Thanks Bernat
