### ISSUE TITLE
"analog/digital reading" watcher

### ISSUE THREAD

**Issue by maprzybylla** [bromagosa/Snap4Arduino#147]
Hi, is there any way to keep the “watchers” for input values after a program was closed and is opened again? What happens is that instead of e.g. “sprite analog reading 1” I only see “sprite 0” when opening a saved program later (screenshot attached). I can’t delete or reconnect it. Are you aware of this problem? Is there a known workaround?

Kind regards,
Mareen
<img width="168" alt="screen shot 2017-03-21 at 10 02 19" src="https://cloud.githubusercontent.com/assets/9349120/24140036/d400726c-0e1e-11e7-83d2-9cd1e4d31115.png">

**Comment by bromagosa** [comment]
Hi Mareen, I had never noticed this until right now. I'll take a look, thanks for reporting it!

**Comment by bromagosa** [comment]
It's fixed in the dev version now. I should definitely start thinking about releasing 1.2.3 soon.
