### ISSUE TITLE
Timeout and Buffer Issue

### ISSUE THREAD

**Issue by rhlgupta** [bromagosa/Snap4Arduino#148]
@MMSequeira @bromagosa @hasso @jguille2 @pierre-rouanet 

Issue 1:
I have created an android build of snap4arduino and in that lot of time, I get a message board had been disconnected when I run a project. I want to know, how can I increase the timeout for Arduino connection. This problem is generally seen when I use digital read and analog read blocks.

Issue 2:
When I add cases to firmata to directly call digitalRead and analogRead and add corresponding code in js at make block section. I get a message that buffer has not been initialized when I run a project

Both of these problems are seen in android build and not in desktop build. Need snap4arduino to run in android asap so help is needed.

**Comment by bromagosa** [comment]
@rhlgupta I don't know how to say it any more. This is **not** a user-ready version :(

I'm actively working on it as we speak, and a pre-alpha is scheduled to be released by mid-April.

I'm only taking bug reports for products that are released to the public, not for ones in development that, obviously, will have bugs and missing features, which is exactly why they're not released yet.

Also, I'd appreciate it if you didn't quote all contributors to the project all the time :(
