### ISSUE TITLE
Doing a silent install - Windows 10

### ISSUE THREAD

**Issue by CCEffect** [bromagosa/Snap4Arduino#149]
I'm an IT Director for a school and need to install Snap4Arduino on about 30 lab computers all running Windows 10. Is it possible to do a silent install of the desktop version? My attempts of running the executable with /s /q /silent /quiet has not worked. 

Any help you can give is GREATLY appreciated.

**Comment by bromagosa** [comment]
I'm using Inno Setup to build the Windows installers, and from [reading its documentation](http://www.jrsoftware.org/ishelp/topic_setupcmdline.htm#SILENT) I'm guessing `/silent` and `/verysilent` are the ones you're probably looking for.

**Comment by bromagosa** [comment]
I understand the solution worked. I'm closing this now.
