### ISSUE TITLE
Translation of Snap! basic elements

### ISSUE THREAD

**Issue by jan-gerard** [bromagosa/Snap4Arduino#152]
The basic Snap! elements' translations in Snap4Arduino don't seem to be part of this repository. If I fix parts of the Dutch translation in https://github.com/jmoenig/Snap--Build-Your-Own-Blocks, will they become part of Snap4Arduino later as well, or should that be triggered/synced/committed/requested somehow?

**Comment by jguille2** [comment]
Hi @jan-gerad,
And don't worry about sync. Snap4Arduino is built from Snap! And all translations, fixes and new features will be available in the next version.
Thanks

Joan
