### ISSUE TITLE
snap4arduino is stuck during bluetooth connection.

### ISSUE THREAD

**Issue by lsirikh** [bromagosa/Snap4Arduino#163]
Hi.

I asked the question related with bluetooth connection yesterday.

I managed to connect snap4arduino with the bluetooth in my notebook(LG gram).

Today, I tried this one on my desktop computer with a bluetooth dongle(204BT bluetooth CSR4.0, NEXT).

But as I already said, snap4arduino is stuck during bluetooth connection with message window( 'Connecting board at port COM9' ; my computer appropriated bluetooth ports to COM10 and COM9).

Does anyone know to solve this problem?

Please help me

**Comment by DenysZaytsev** [comment]
Hey there. 

One of your COM ports is outgoing and another one is incoming connection, so maybe you've chosen a wrong port, try connecting to other COM (COM10 in your case).

Also right after you clicked connect - try pressing a reset button on the Arduino, it helps!

Thanks,
D.
