### ISSUE TITLE
Auto-upload Firmata to the board if it isn't there

### ISSUE THREAD

**Issue by edutec** [bromagosa/Snap4Arduino#18]
_From @bromagosa on July 31, 2014 7:50_

This is tricky. Each OS would need its own different avrdude version and a different upload script.

Also, #8 is a prerequisite for this one.

_Copied from original issue: edutec/Snap4Arduino-old-huge#9_

**Comment by bromagosa** [comment]
Check https://www.npmjs.com/package/stk500 and https://www.npmjs.com/package/avrgirl-arduino
