### ISSUE TITLE
Chrome extension doesn't save settings.

### ISSUE THREAD

**Issue by DavidGasku** [bromagosa/Snap4Arduino#183]
Both manual and through chrome store. Doesn't keep logged in for the user.

**Comment by bromagosa** [comment]
Yes, I'm afraid that's an issue with how Chrome apps handle local storage... :(

Does the web version work for you? You just need to install the [Chrome connector extension](http://snap4arduino.rocks/#plugin) and you'll be able to use Snap4Arduino from http://snap4arduino.rocks/run

**Comment by jguille2** [comment]
Hi @DavidGasku,
I close this issue. As Bernat said, after Desktop versions, we recommend [Chrome-chromium connector extension](http://snap4arduino.rocks/#plugin) to use with [Snap4Arduino online](http://snap4arduino.rocks/run)
Joan
