### ISSUE TITLE
Missing link: https://github.com/bromagosa/Snap4Arduino/releases/download/1.2.3/Snap4Arduino_chromium-plugin-1.2.3.crx

### ISSUE THREAD

**Issue by ToonTalk** [bromagosa/Snap4Arduino#185]
From http://snap4arduino.rocks/#plugin

While https://github.com/bromagosa/Snap4Arduino/releases/download/1.2.3/Snap4Arduino_web-chromium_1.2.3.zip seems to contain the extension.

**Comment by jguille2** [comment]
Hi @ToonTalk ,

Now, the lost link is fixed ([https://github.com/bromagosa/Snap4Arduino/releases/download/1.2.3/Snap4Arduino_chromium-plugin-1.2.3.crx](https://github.com/bromagosa/Snap4Arduino/releases/download/1.2.3/Snap4Arduino_chromium-plugin-1.2.3.crx))

Yes, [zip file](https://github.com/bromagosa/Snap4Arduino/releases/download/1.2.3/Snap4Arduino_web-chromium_1.2.3.zip) is ok, and it has all (plugin and web files), but [crx file](https://github.com/bromagosa/Snap4Arduino/releases/download/1.2.3/Snap4Arduino_chromium-plugin-1.2.3.crx) is lighter if you are using an online version.

Joan
