### ISSUE TITLE
Translation and menu styles for RTL languages like Persian

### ISSUE THREAD

**Issue by Erfankam** [bromagosa/Snap4Arduino#190]
Hi. Recently we decide to use **Snap4Arduino** project with menu translated to Persian. But when we use Persian phrases inside GUI, All of them are left to right. I use a **lang-xx.js** file and successfully use that for translating source words and phrases but in a wrong direction. I mean. for example I want the tool or block section in GUI appear in right side of the GUI not left and phrases start from right side of the text boxes instead and so on.
Is it possible to set a _RTL_ feature inside code to rearrange menu styles and texts from right to left?
Thanks.

**Comment by bromagosa** [comment]
Roping @jmoenig here, because I'm pretty sure Snap! does support RTL alphabets :)
