### ISSUE TITLE
Automatic translation of Snap programs to Arduino C

### ISSUE THREAD

**Issue by ToonTalk** [bromagosa/Snap4Arduino#191]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Codification&editMode

shows how Snap! programs can be converted to C (and other languages). My guess is that enhancing this example to generate C code suitable for the Arduino IDE should not be too difficult.  Has this been attempted? If not, I'll have a go.

The obvious utility of this would be that Snap4Arduino programs can be downloaded into an Arduino to run locally.

**Comment by bromagosa** [comment]
Not only attempted, but [done](http://blog.s4a.cat/2015/06/09/Snap4Arduino-Arduino-sketch-generation.html) ;)

Although, of course, most of the interesting things in Snap! will never be translatable into C.
