### ISSUE TITLE
NETWORKERROR on launch

### ISSUE THREAD

**Issue by julienrat** [bromagosa/Snap4Arduino#197]
Hello
probably due a new adresse of snap4arduino.org --> snap4arduino.rocks i have got this error at launch 

NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://snap4arduino.org/downloads/LATEST'

**Comment by jguille2** [comment]
Hi @julienrat,
We know this problem. Very soon (we are re-testing to avoid possible problems), we'll release 1.2.4 to fix this bug. You can use (and test with us) [this version](https://github.com/bromagosa/Snap4Arduino/releases).
Thank!

Joan
