### ISSUE TITLE
Help me please!!  Snap4Arduino  can't via Bluetooth

### ISSUE THREAD

**Issue by codepada** [bromagosa/Snap4Arduino#205]
<img width="232" alt="snaperror" src="https://user-images.githubusercontent.com/33388356/32412869-f56c927e-c236-11e7-8bc0-850842c9fbbc.png">

Board Arduino LEONARDO R3
HC-06 JY-MCU
Battery 9V

MacOS Sierra 10.12.6
Snap4Arduino  1.2.4
Arduino IDE 1.8.3

StandardFirmata
Baud rate 57600
NAME Bluetooth  WHATEVER

I follow this step by : https://github.com/bromagosa/Snap4Arduino/wiki/Autonomy-via-Blueetooth

**Comment by codepada** [comment]
Thank you bromagosa for answer

**Comment by jguille2** [comment]
Hi @caimunnoi ,
Then, is working for you when you are plugged? And can you test this with other boards?

I'm sorry but I haven't got any Leonardo board... and I can't test your configuration.

Tell us your results... maybe we can write down more details... or we can close this issue.

Thanks,

Joan

**Comment by jpliew** [comment]
I can confirm that Leonardo is working properly using USB cable. @caimunnoi  you might want to check with USB cable first like @jguille2 said.
