### ISSUE TITLE
CodeMaster – Automatic Assessment and Grading of Snap! and App Inventor Programs

### ISSUE THREAD

**Issue by JeanHauck** [bromagosa/Snap4Arduino#209]
Hello,

we are excited to launch and share our CodeMaster, a free web application that in a problem-based learning context allows to automatically assess and grade projects programmed with App Inventor and Snap!.

CodeMaster is available in English and Brazilian Portuguese.

More information: http://www.computacaonaescola.ufsc.br/?page_id=2523&lang=en

Or just try it out: http://apps.computacaonaescola.ufsc.br:8080

The tool has been developed by two students as part of their final undergraduate thesis in the context of our initiative Computação na Escola at the Federal University of Santa Catarina/Brazil. Based on first feedback, we are planning to continue the development of the tool as part of future student’s theses. Any suggestions are very welcome.

Best regards,

Christiane, Aldo and Jean

**Comment by jguille2** [comment]
Hi Jean,
Thanks for your report.
We saw your notice and we are testing (you know Snap4Arduino team are all Snapers!!)

Surely we can use your work... and we will send our feedback.
Go on and thanks for your work! We are convinced that Snap! is a wonderful tool for education.

Joan

**Comment by JeanHauck** [comment]
Thanks @jguille2 !
