### ISSUE TITLE
Cryptic error message when trying to run Snap4Arduino twice

### ISSUE THREAD

**Issue by neuwirthe** [bromagosa/Snap4Arduino#210]
I am trying to run Snap4Arduino (downloaded the binary from snap4arduino.rocks) om MacOS 10.13.1,
but I cannot be started. I get an error:
The application "Snap4Arduino.app" can't be started -47
How can the issue be resolved?

**Comment by neuwirthe** [comment]
It turns out that the error occurred because there was another instance of Snap4Arduino already running. So it was my fault, but the error message could possibly be more informative.

**Comment by bromagosa** [comment]
Hi Erich!

I'm afraid this error message comes from nwjs.io, the underlying engine that runs Snap4Arduino, and I don't think it can be changed. I will take a look anyway.

Thanks for reporting! :)
