### ISSUE TITLE
Connect, disconnect, connect fails in plug-in

### ISSUE THREAD

**Issue by ToonTalk** [bromagosa/Snap4Arduino#218]
I succeeded with 'connect to arduino at /dev/ttyACM0' on a Raspberry Pi connected to an Uno. I then disconnected. Then when connect again I get "Could not talk to Arduino at port ...". After that reloading or resetting the Arduino doesn't fix the problem. Reloading the page and reconnecting the USB cable does fix the problem.

**Comment by jguille2** [comment]
Are you working with the 'embedded' version?

**Comment by ToonTalk** [comment]
The CRX plugin since I want to add some new blocks in JavaScript.
