### ISSUE TITLE
Some help to start diving in the code?

### ISSUE THREAD

**Issue by hpavon** [bromagosa/Snap4Arduino#22]
Hi!

My apologies in advance if this is not the right place for this request -I'm a newb here.

I'm working in educational tech projects for kids. We use Makeblock for primary students and bare Arduino for secondary. The thing is that we are looking for a graphic programming environment that suits both, but none seems to fit: too limited, too dull for kids, incomplete sets of blocks,...

I wold love to make my own blocks for programming Makeblock, but not just build them in the Snap! BYOB fashion. I want to make it your way, a sort of "Snap4Makeblock".

My problems is that after looking at your repo here and trying to figure out how your blocks are programmed, I just don't know where to start. The time I can dedicate to this project is limited and I would really appreciate some hints on how to start with this. Then maybe I could write a sort of starter's guide for messing around with Snap/S4A and add it to your repo, that would be cool.

Thanks in advance and I hope we talk again soon,

Héctor

PS: you can write back in spanish, and if you prefer you can email me at hpavon@gmail.com.

**Comment by bromagosa** [comment]
Basically, all Snap4Arduino does is extend Snap<i>!</i> by means of proxy patterns.

All proxied functions are located under `snap/s4a` inside corresponding files, and these files are loaded in the proper order in `snap/s4a.html`.

The files where blocks are defined, as in Snap<i>!</i>, are:
- **objects.js** → Here we write the block specs, in particular they're ll in `SpriteMorph.prototype.initArduinoBlocks`. Later on, we push them to the blocks palette in `SpriteMorph.prototype.blockTemplates`
- **threads.js** → In this file we define which functions get triggered by these blocks. Each block must have a function in the `Process` prototype that shares name with the block selector.
- **blocks.js** → Here we define label parts, such as servo directions or pin modes.

Hope it helps! :)

_For info on building, please see the [README.md](https://github.com/edutec/Snap4Arduino/blob/master/README.md) file in this repo._
