### ISSUE TITLE
cant download 'Wifi to Serial Sketch'

### ISSUE THREAD

**Issue by duyaTech** [bromagosa/Snap4Arduino#222]
Sadly I cant download 'Wifi to Serial Sketch' from [https://github.com/bromagosa/Snap4Arduino/wiki/Autonomy-via-Wifi](url), which is in the field of 'Pushing the "Wifi to Serial" Sketch'. Could anyone tell me where I can get this?

**Comment by bromagosa** [comment]
You're right, since snap4arduino.org doesn't exist anymore, the file was gone. Sorry about that!

I've pushed the file to this repo and changed the URL in the wiki page to point to it.

Thanks for reporting! :)

**Comment by duyaTech** [comment]
You are welcome. This project is really amazing. Just it still has some problems to be solved in the #224 issue which I asked yesterday. It looks like I havent connect the wire correctly. Could you give me some advice？
