### ISSUE TITLE
Costumes -> Camera windows won't close.

### ISSUE THREAD

**Issue by jpliew** [bromagosa/Snap4Arduino#226]
![image](https://user-images.githubusercontent.com/1773147/35785774-290550fc-0a77-11e8-91a3-aab242b93b99.png)

**Comment by jguille2** [comment]
Thanks @jpliew,

You are right. This is an issue of 1.2.4 version (a draft of the camera feature implemented later in Snap!). And this is fixed into current dev version (soon released).

Thanks again,

Joan
