### ISSUE TITLE
Mac OSX version still 1.2.4

### ISSUE THREAD

**Issue by aplazaris** [bromagosa/Snap4Arduino#233]
I am downloading the new version - the zip file's name states "1.2.5", but the Snap4Arduino still shows 1.2.4!

**Comment by bromagosa** [comment]
Hmm... does it say 1.2.4 in the "About Snap4Arduino" dialog or just in the title bar?

![image](https://user-images.githubusercontent.com/1016697/36442096-ec955f72-1674-11e8-9ace-7d1b72015eac.png)

**Comment by aplazaris** [comment]
![snap4arduino](https://user-images.githubusercontent.com/36012504/36442481-95fc27e0-167e-11e8-8ad1-c64aac777cbd.png)
Weird! Have a look at the screenshot attached.

**Comment by bromagosa** [comment]
I see. Don't worry, we'll take a look and fix it. Your version is 1.2.5, but I forgot to set the version number in the package, that's all :)

**Comment by bromagosa** [comment]
I've uploaded a patched version. Thanks for noticing and reporting! :)
