### ISSUE TITLE
Stepper support

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/Snap4Arduino#24]
It seems firmata.js supports steppers, so let's take a look at this and implement blocks to use them:

https://github.com/jgautier/firmata/blob/master/lib/firmata.js#L1409

It seems we're going to need AdvancedFirmata for these, so this should probably be a somewhat hidden feature or a loadable library.

**Comment by DavidGasku** [comment]
What's the status about this feature?
Any way to make it work?
