### ISSUE TITLE
Wrong frequencies in SnapJr library

### ISSUE THREAD

**Issue by DavidGasku** [bromagosa/Snap4Arduino#240]
Hi, I think the SnapJr library is a great idea.
Playing with it, I noticed that the notes in the sound library are wrong
The values should be 60, 62, 64, 65, 67, 69, 71

**Comment by jguille2** [comment]
Thanks David,
This has already fixed by @bromagosa [today](https://github.com/bromagosa/Snap4Arduino/commit/50cf02fd69282d2de20398c7ef2b4153caad8cf6).

So dev version (and of course next version will) have the right notes.

Thanks for your report
Joan
