### ISSUE TITLE
Can S4A resend the REPORT_FIRMWARE message...

### ISSUE THREAD

**Issue by segertonGH** [bromagosa/Snap4Arduino#243]
...if no printFirmwareVersion() reply has been received after a connection has been made? Say after two REPORT_VERSION messages?  This would seem to fix Bluetooth connection issues which miss the REPORT_FIRMWARE message (this can be handled from the Firmata side on the Arduino but is messy).

All the best,

Simon.

**Comment by bromagosa** [comment]
That sounds definitely feasible. I'm super busy with other projects at the moment but I'll try to find some time to look into it.

**Comment by segertonGH** [comment]
The issue can be reproduced via a USB connection by installing a 10uf capacitor between the reset line and ground.  This prevents the Arduino from resetting when S4A tries to connect (simulating the scenario for (some/most?) Bluetooth connections).
