### ISSUE TITLE
snap4arduino error

### ISSUE THREAD

**Issue by basilhsk7** [bromagosa/Snap4Arduino#253]
hi,
when im trying to connect im. getting error connecting the board. [object Object].... 
what this error means? 
im getting this a lot when im trying to connect via bluetooth

**Comment by wydmynd** [comment]
+1 this, connecting by USB. cannot clear problem by disconnecting & reconnecting. 
confirm com port exists via device manager. closing & reopening the software does not solve. also not switching USB port. only rebooting computer.  windows 7 PC. arduino using original windows driver atmega16u2.
