### ISSUE TITLE
Links to LCD not worked

### ISSUE THREAD

**Issue by ghost** [bromagosa/Snap4Arduino#265]
[LCD Display](http://vps34736.ovh.net/LCD-Snap4Arduino.zip) :: [blog post](http://blog.s4a.cat/2015/03/24/LCD-Library-for-Snap4Arduino.html) on main page no more worked :(

Where can I download this library and read aboit it?

**Comment by bromagosa** [comment]
I believe @jguille2 has just fixed this in the project website :)
