### ISSUE TITLE
Cloud: Not receiving confirmation e-mail

### ISSUE THREAD

**Issue by gmitter** [bromagosa/Snap4Arduino#273]
I'm starting to work with my students and i just created all their logins. From one of these users (escolamais1a) I'm not receiving the verification email. I'm thinking maybe I mistyped the e-mail address? It should be login@escolamais.com

If not, why am I not receiving the confirmation e-mail only for this user?
Thanks in advance.

**Comment by jguille2** [comment]
Hi @gmitter,

I ping @bromagosa to check this. But note that Snap4Arduino is using the Snap! cloud. So, issues on the cloud must be reported to Snap! project.

Thanks,

Joan
