### ISSUE TITLE
New language files (Ukrainian and Russian)

### ISSUE THREAD

**Issue by SyavsoN** [bromagosa/Snap4Arduino#28]
Hi there!

Could you add two new language files (Ukrainian and Russian) to repository?

**Ukrainian** - [https://github.com/SyavsoN/Snap4Arduino/blob/master/snap/s4a/s4a-lang-uk.js](url)

**Russian** - [https://github.com/SyavsoN/Snap4Arduino/blob/master/snap/s4a/s4a-lang-ru.js](url)

Bets regards,
Yaroslav

**Comment by bromagosa** [comment]
Thanks a lot! I'm integrating these in the next release! :)

**Comment by SyavsoN** [comment]
Dear Bernat,

Could you tell me if you can integrate Ukrainian language for Snap, if I make the translation?

**Comment by bromagosa** [comment]
Hi Yaroslav,

it'd be easier if you just send a pull request straight to https://github.com/jmoenig/Snap--Build-Your-Own-Blocks :)

**Comment by SyavsoN** [comment]
Hi Bernat,

Thank you for your suggestion. I'm new to GitHub and version control, so your comment was very helpful, thank you!
