### ISSUE TITLE
Project Name Problem

### ISSUE THREAD

**Issue by tguneysu** [bromagosa/Snap4Arduino#283]
When a new poject is started, the project name in English is "untitled".
Afterwards if the language is changed to any other one, the name gets changed to the translated equivalent of the "untitled".
Then if the language is changed again, the project name gets stuck in the previous language's selection.
Not a big deal, but just wanted to report it so it does not confuse users.
I hit arabic by mistake and had to look at an arabic "untitled" until I saved te project.

**Comment by bromagosa** [comment]
Hi, Turgut. I believe this is a bug in Snap! itself, not just in Snap4Arduino.

There's actually a pull request by @jguille2 since 2017 waiting for someone to review: https://github.com/jmoenig/Snap/pull/1674

(closing because this is Snap!'s bug...)
