### ISSUE TITLE
Cancelling Import crashes Windows app

### ISSUE THREAD

**Issue by NickTulett** [bromagosa/Snap4Arduino#284]
If you select Import from the menu, then Cancel the dialog, the app crashes (process dies after ~500ms, no warnings or errors)

v4.2.1.4

Windows 10 Home 64-bit

**Comment by jguille2** [comment]
Oh! @NickTulett  I hadn't seen this.

But, you can test our new [Snap4Arduino 5.0 version](https://github.com/bromagosa/Snap4Arduino/releases/tag/5.0). It will be released in a few days. And I think this issue is over.

Joan
