### ISSUE TITLE
v5.0 should have a "browser" option for Save As

### ISSUE THREAD

**Issue by NickTulett** [bromagosa/Snap4Arduino#287]
The file Open menu option has Cloud, Examples, Browser and Computer.
File Save As has Cloud and Computer (which just exports the project to Downloads by default).

It should include Browser and be able to use the same folder as v4.x

**Comment by bromagosa** [comment]
Browser storage has been deprecated in Snap! 5.0, and thus also in Snap4Arduino.

However, if you had projects stored in browser, the tab will still show up so you can recover them.

**Comment by NickTulett** [comment]
Ah OK. I will take a look at the release notes, thanks!
