### ISSUE TITLE
Export Failed: ReferenceError: owner is not defined

### ISSUE THREAD

**Issue by neurodude** [bromagosa/Snap4Arduino#29]
When I click export project.  I am trying to use this in an offline educational environment so I don't have access to cloud sync.

**Comment by neurodude** [comment]
So it seems to have happened after I switched to arduino translatable project.  I can't seem to get it to actually translate to arduino code either.

**Comment by chrisclaynz** [comment]
I'm having the same issue here...

**Comment by bromagosa** [comment]
Thanks for reporting, I've just fixed this and published a new release (1.1.2 beta).
