### ISSUE TITLE
snap4arduino build environment

### ISSUE THREAD

**Issue by sxcem** [bromagosa/Snap4Arduino#290]
sir：

what‘s Snap4Arduino build environment ？

best regards！

**Comment by jguille2** [comment]
Hi,
You can see all the building process inside our repo (_build_ and _prepare_ scripts).

Anyway, Snap4Arduino is implemented in _nw.js_ (based in _chromium_ and _node.js_). We use the _nwbuilder_ to do it.

Any question more will be welcome.

Joan

**Comment by sxcem** [comment]
jguille2，Thanks very much！
