### ISSUE TITLE
Cannot play mp3.

### ISSUE THREAD

**Issue by levindu** [bromagosa/Snap4Arduino#30]
I've tried the latest release in Arch Linux 64bits and Windows XP. Both cannot play mp3 sound.

**Comment by bromagosa** [comment]
Can you try the same thing in regular Snap?

**Comment by levindu** [comment]
I tried the regula Snap ( http://snap.berkeley.edu/snapsource/snap.html ), which can play the MP3 files both builtin or dropped to it.

**Comment by edutec** [comment]
No problems here with version 1.1.2 in Debian stable. I'll try in Windows
ASAP.

Best regards,

2016-03-25 3:36 GMT+01:00 Levin Du notifications@github.com:

> I tried the regula Snap ( http://snap.berkeley.edu/snapsource/snap.html
> ), which can play the MP3 files both builtin or dropped to it.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/edutec/Snap4Arduino/issues/30#issuecomment-201112596

## 

_Víctor Casado_
Equip de recerca (Edutec)
victorct@citilab.eu

FUNDACIÓ PEL FOMENT DE LA
SOCIETAT DEL CONEIXEMENT
CORNELLÀ

Citilab Cornellà | http://citilab.eu | Pl. Can Suris s/n | 08940 Cornellà
de Llobregat | Barcelona

En compliment de la Llei Orgànica de Protecció de Dades de Caràcter
Personal (LOPD), l’informem que les seves dades de contacte han estat
incorporades en un fitxer titularitat de FUNDACIÓ PEL FOMENT DE LA SOCIETAT
DEL CONEIXEMENT (CITILAB). La finalitat d’aquest fitxer és la de mantenir
la relació amb els usuaris dels diferents oferts, inscripció als cursos i a
les activitats organitzades, facilitar la tramitació d’informació i
notificacions comercials i administratives, i en el cas de que vostè ho
hagi sol·licitat, l’enviament de publicitat relativa als serveis oferts.
FUNDACIÓ PEL FOMENT DE LA SOCIETAT DEL CONEIXEMENT (CITILAB) assegura la
confidencialitat de les dades aportades i garanteix que, en cap cas, seran
cedides per cap altre ús sense que hi hagi un consentiment previ i exprés
per part seva.

Per exercir els drets d’accés, rectificació, cancel·lació i oposició
previstos en la llei, pot adreçar-se mitjançant correu postal a FUNDACIÓ
PEL FOMENT DE LA SOCIETAT DEL CONEIXEMENT (CITILAB), Ref. Protecció de
Dades, Pl. Can Suris S/N, 08940, Cornellà de Llobregat, Barcelona, o bé
exercir els drets assenyalats mitjançant l’enviament de la seva petició al
correu electrònic avislegal@citilab.eu, indicant en l’assumpte del correu
“Ref. Protecció de Dades” (acreditant degudament la seva identitat).

**Comment by bromagosa** [comment]
We can't fix this issue for now: https://github.com/nwjs/nw.js/issues/4492#issuecomment-192047570

Software patents... :(

**Comment by bromagosa** [comment]
@levindu for now, the recommended way to go is to use a free format such as OGG.

**Comment by levindu** [comment]
@bromagosa  Thanks for the effort.
