### ISSUE TITLE
i2c read block is to be fixed

### ISSUE THREAD

**Issue by lhdangerous** [bromagosa/Snap4Arduino#305]
According to johnny-5 document, There should be 'how many bytes' for the 3rd argument of 'i2cReadOnce()' function.
But your i2c extension doesn't have this and acts unexpected way.
Can you update this please?

**Comment by jguille2** [comment]
Hi August @lhdangerous

I will check this (especially in the words used) but 3 initial comments (I don't have much time now)

- The first _slot_ of the "i2c read" block is really the "how many bytes" argument.
- The "register" argument is missing... and I haven't needed in any case (checking Arduino libraries). In fact, if you read carefully `i2cReadOnce` docs, there are 4 arguments (address, register, bytesToRead, callback) but when there are 3, the register is bypassed and the seconc is the "bytesToRead".
- Anyway, you can make your own workaround. You can see (editing the blocks) there are JS blocks. And you can do whatever you need and make your own block with all 4 arguments.

Joan
