### ISSUE TITLE
Can't login to snap cloud

### ISSUE THREAD

**Issue by DavidGasku** [bromagosa/Snap4Arduino#313]
Trying to login with my snap account fails (https://snap.berkeley.edu/api/v1)
Is that a problem on my side? I can login in snap site, though

**Comment by jguille2** [comment]
Hi David,

Sorry, it's not on your side!
Snap site is making changes and there is an issue with the Snap4Arduino connection. Snap! is running ok.

I'm tracking this.

Joan

**Comment by DavidGasku** [comment]
Thanks Joan!

**Comment by jguille2** [comment]
Hi David,

Login issue has was fixed at the moment.
But still you couldn't access to your "Project list"... And now is full fixed (thanks @bromagosa )

And also thanks @DavidGasku  for reporting!

Joan
