### ISSUE TITLE
HiS4A not working on an Android 10 device

### ISSUE THREAD

**Issue by Dario-64** [bromagosa/Snap4Arduino#315]
Hi, today I wanted to try HiS4A on my Android 10 device.
When I installed it, it doesn't open. Could someone help me?

**Comment by jguille2** [comment]
Hi Dario.

We are not behind that project. You can go to http://s4a.cat/index_es.html and contact them. But you know Scratch4Arduino is not under developement and so, that android app is not updated too.
And yes, I see it is not running on current Android versions.

Note that Snap4Arduino is using the same http protocol, and you can build  similar apps (or just web pages) using it. All the info is in http://snap4arduino.rocks/#http

Joan
