### ISSUE TITLE
Issue with nwjs

### ISSUE THREAD

**Issue by Ducks84** [bromagosa/Snap4Arduino#317]
Hi everyone,
I'm using a Macbook Pro M1 with MacOS 13.0.1

I can't install snap4arduino, i have a "nwjs" error.

Here's the report:

> -------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               nwjs [81939]
Path:                  /private/var/folders/*/Snap4Arduino.app/Contents/MacOS/nwjs
Identifier:            com.nw-builder.snaparduino
Version:               Version 8.1.0 (8.1.0)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-11 21:21:05.9555 +0100
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Anonymous UUID:        91774B21-1F74-1BF6-8FFF-945132DAA203

Sleep/Wake UUID:       83373154-3187-4D18-9948-D2BFA9FE4855

Time Awake Since Boot: 33000 seconds
Time Since Wake:       1585 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff8ad21e9a8 ???
1   libsystem_kernel.dylib        	    0x7ff81df5f30e __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff81df96f7b pthread_kill + 263
3   libsystem_c.dylib             	    0x7ff81dee0ca5 abort + 123
4   libsystem_c.dylib             	    0x7ff81dee0e13 abort_report_np + 180
5   nwjs                          	       0x104bb2978 0x104bb2000 + 2424
6   nwjs                          	       0x104bb284c main + 236
7   dyld                          	       0x204d8b310 start + 2432

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7fff05750 0x7ff7fff01000 + 18256
1   runtime                       	    0x7ff7fff1166c 0x7ff7fff01000 + 67180
2   runtime                       	    0x7ff7fff1306c 0x7ff7fff01000 + 73836

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00007fa0fb008800  rsi: 0x0000000000000003  rbp: 0x0000000000000000  rsp: 0x00007ff8615dc258
   r8: 0x0000000204e292c0   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x00007ff8615dc250
  r12: 0x0000000000000103  r13: 0x00000000000000de  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: <unavailable>       rfl: 0x0000000000000283
 tmp0: 0xffffffffffffffff tmp1: 0x00007ff8ad21e97c tmp2: 0x00007ff81df5f304

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff81df57000 -     0x7ff81df90ff7 libsystem_kernel.dylib (*) <0c2fd2c9-777c-3355-b70f-7b1b6e9d1b0b> /usr/lib/system/libsystem_kernel.dylib
    0x7ff81df91000 -     0x7ff81df9cff7 libsystem_pthread.dylib (*) <13b5e252-77d1-31e1-888d-1c5f4426ea87> /usr/lib/system/libsystem_pthread.dylib
    0x7ff81de5f000 -     0x7ff81dee7fff libsystem_c.dylib (*) <5efaf10b-2ec1-32ed-b077-80125e552c8d> /usr/lib/system/libsystem_c.dylib
       0x104bb2000 -        0x104bdcfff com.nw-builder.snaparduino (Version 8.1.0) <4c4c44cd-5555-3144-a1ca-127cbbfb16b4> /private/var/folders/*/Snap4Arduino.app/Contents/MacOS/nwjs
       0x204d85000 -        0x204e1cfff dyld (*) <28fd2071-57f3-3873-87bf-e4f674a82de6> /usr/lib/dyld
    0x7ff7fff01000 -     0x7ff7fff30fff runtime (*) <6f797d84-b330-3656-9a0d-7b3dbd3f8a07> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=172.5M resident=0K(0%) swapped_out_or_unallocated=172.5M(100%)
Writable regions: Total=174.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=174.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            18.1M       10 
MALLOC guard page                   96K        4 
Rosetta Arena                     4096K        2 
Rosetta Generic                    956K      236 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.1M        8 
__DATA                             312K       42 
__DATA_CONST                       243K       33 
__DATA_DIRTY                        72K       23 
__LINKEDIT                       166.7M        8 
__OBJC_RO                         65.1M        1 
__OBJC_RW                         1980K        2 
__TEXT                            5932K       44 
dyld private memory                256K        1 
mapped file                        4.0G     1246 
shared memory                       16K        1 
unshared pmap                     2288K        2 
===========                     =======  ======= 
TOTAL                              4.5G     1672 

-----------
Full Report
-----------

{"app_name":"nwjs","timestamp":"2023-01-11 21:21:06.00 +0100","app_version":"Version 8.1.0","slice_uuid":"4c4c44cd-5555-3144-a1ca-127cbbfb16b4","build_version":"8.1.0","platform":1,"bundleID":"com.nw-builder.snaparduino","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.0.1 (22A400)","roots_installed":0,"name":"nwjs","incident_id":"92F589DC-24D5-4705-9682-1D4C638C2B6D"}
{
  "uptime" : 33000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 4684,
  "osVersion" : {
    "train" : "macOS 13.0.1",
    "build" : "22A400",
    "releaseType" : "User"
  },
  "captureTime" : "2023-01-11 21:21:05.9555 +0100",
  "incident" : "92F589DC-24D5-4705-9682-1D4C638C2B6D",
  "pid" : 81939,
  "translated" : true,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-01-11 21:21:05.7972 +0100",
  "procStartAbsTime" : 805316606211,
  "procExitAbsTime" : 805320315751,
  "procName" : "nwjs",
  "procPath" : "\/private\/var\/folders\/*\/Snap4Arduino.app\/Contents\/MacOS\/nwjs",
  "bundleInfo" : {"CFBundleShortVersionString":"Version 8.1.0","CFBundleVersion":"8.1.0","CFBundleIdentifier":"com.nw-builder.snaparduino"},
  "storeInfo" : {"deviceIdentifierForVendor":"5F9CB4D9-A29C-5FB0-B3A8-6CECE0B3E9FC","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.nw-builder.snaparduino",
  "crashReporterKey" : "91774B21-1F74-1BF6-8FFF-945132DAA203",
  "wakeTime" : 1585,
  "sleepWakeUUID" : "83373154-3187-4D18-9948-D2BFA9FE4855",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":444158,"threadState":{"flavor":"x86_THREAD_STATE","rbp":{"value":0},"r12":{"value":259},"rosetta":{"tmp2":{"value":140703631274756},"tmp1":{"value":140706033297788},"tmp0":{"value":18446744073709551615}},"rbx":{"value":0},"r8":{"value":8671892160,"symbolLocation":0,"symbol":"_main_thread"},"r15":{"value":22},"r10":{"value":0},"rdx":{"value":0},"rdi":{"value":140329382610944},"r9":{"value":0},"r13":{"value":222},"rflags":{"value":643},"rax":{"value":0},"rsp":{"value":140704762151512,"symbolLocation":456,"symbol":"__sFX"},"r11":{"value":140704762151504,"symbolLocation":448,"symbol":"__sFX"},"rcx":{"value":0},"r14":{"value":6},"rsi":{"value":3}},"queue":"com.apple.main-thread","frames":[{"imageOffset":140706033297832,"imageIndex":0},{"imageOffset":33550,"symbol":"__pthread_kill","symbolLocation":10,"imageIndex":1},{"imageOffset":24443,"symbol":"pthread_kill","symbolLocation":263,"imageIndex":2},{"imageOffset":531621,"symbol":"abort","symbolLocation":123,"imageIndex":3},{"imageOffset":531987,"symbol":"abort_report_np","symbolLocation":180,"imageIndex":3},{"imageOffset":2424,"imageIndex":4},{"imageOffset":2124,"symbol":"main","symbolLocation":236,"imageIndex":4},{"imageOffset":25360,"symbol":"start","symbolLocation":2432,"imageIndex":5}]},{"id":444187,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18256,"imageIndex":6},{"imageOffset":67180,"imageIndex":6},{"imageOffset":73836,"imageIndex":6}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703631241216,
    "size" : 237560,
    "uuid" : "0c2fd2c9-777c-3355-b70f-7b1b6e9d1b0b",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703631478784,
    "size" : 49144,
    "uuid" : "13b5e252-77d1-31e1-888d-1c5f4426ea87",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703630225408,
    "size" : 561152,
    "uuid" : "5efaf10b-2ec1-32ed-b077-80125e552c8d",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4374339584,
    "CFBundleShortVersionString" : "Version 8.1.0",
    "CFBundleIdentifier" : "com.nw-builder.snaparduino",
    "size" : 176128,
    "uuid" : "4c4c44cd-5555-3144-a1ca-127cbbfb16b4",
    "path" : "\/private\/var\/folders\/*\/Snap4Arduino.app\/Contents\/MacOS\/nwjs",
    "name" : "nwjs",
    "CFBundleVersion" : "8.1.0"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8671219712,
    "size" : 622592,
    "uuid" : "28fd2071-57f3-3873-87bf-e4f674a82de6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703127572480,
    "size" : 196608,
    "uuid" : "6f797d84-b330-3656-9a0d-7b3dbd3f8a07",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703627526144,
  "size" : 21474836480,
  "uuid" : "7b321622-762b-3cdc-9d76-14f1310c0a31"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=172.5M resident=0K(0%) swapped_out_or_unallocated=172.5M(100%)\nWritable regions: Total=174.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=174.5M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nKernel Alloc Once                    8K        1 \nMALLOC                            18.1M       10 \nMALLOC guard page                   96K        4 \nRosetta Arena                     4096K        2 \nRosetta Generic                    956K      236 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.1M        8 \n__DATA                             312K       42 \n__DATA_CONST                       243K       33 \n__DATA_DIRTY                        72K       23 \n__LINKEDIT                       166.7M        8 \n__OBJC_RO                         65.1M        1 \n__OBJC_RW                         1980K        2 \n__TEXT                            5932K       44 \ndyld private memory                256K        1 \nmapped file                        4.0G     1246 \nshared memory                       16K        1 \nunshared pmap                     2288K        2 \n===========                     =======  ======= \nTOTAL                              4.5G     1672 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62fe74515312cd4599bd3c80",
      "factorPackIds" : {
        "MYRIAD_BOOSTS" : "62fe74805312cd4599bd3c81"
      },
      "deploymentId" : 240000006
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,1, BootROM 8419.41.10, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Sep  3 2022 02:35:52 version 20.10.965.9.8.7.129 FWID 01-b0e84a9b
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.
Thunderbolt Bus: Laptop, Apple Inc.

I saw someone had this kind of error, but if someone has a solution I will be happy. 
Otherwise I'll use the online version.

Thanks
Ducks84

**Comment by jguille2** [comment]
I'm sorry about your issue.

I haven't any Mac device and I can not test it.
I see there are a few more downloads of the osx version and it is the first report.

I ask some friends to test it (to reproduce your issue) and I will fix it as soon as possible.

I believe you are having problems... but I also know that there was the same "error" report by some users on the past version (v7) and there was thousands of downloads and people runing on Macs that version. Then I guess is a configuration issue of the Mac?

Continue.... and we'll find a solution for this.

Joan

**Comment by jguille2** [comment]
Hi @Ducks84

I've finally managed to borrow a mac device today... and I've been able to find the problem, fix it and test it :)
https://twitter.com/jguille2/status/1619126474459734017

It is still an unsigned app (you know you have to open Finder and explicitly allow execution... but I think it's fine.
I've also noticed that the first few runs take "too long" to boot...but I'd say that's not a problem.
https://github.com/bromagosa/Snap4Arduino/releases/download/8.1.0/Snap4Arduino_desktop-osx-64_8.1.0.zip

If you can try it, it will be great to have your feedback.

Thanks!
Joan

**Comment by jguille2** [comment]
Closing...
Other tests confirm MAC installation is ok (also with the newest version)
