### ISSUE TITLE
Font size too small & painful for study without option to increase it

### ISSUE THREAD

**Issue by ak117611** [bromagosa/Snap4Arduino#323]
Your s4a software is useless & irritating to eyes coz of uncomfortable font size . When u create settings to increase it , let me know , call me on 9971820630 , my kids & me can start studying it after its done . No people with specs likes to use it as of now

Also check https://github.com/arduino/Arduino/issues/10921

**Comment by bromagosa** [comment]
No free software maintainer should ever reply to rude comments, but anyway...

Go to the gear menu, select `Zoom blocks...`

![imatge](https://github.com/bromagosa/Snap4Arduino/assets/1016697/327be358-8192-427b-9ddf-4a62dae57eb4)

Make your block text as big or small as you want.

![imatge](https://github.com/bromagosa/Snap4Arduino/assets/1016697/f76f7e7d-35eb-4ddf-accf-4bc9228ba774)

**Comment by ak117611** [comment]
Ohh I lost my job due to your font size .... didn't know your superfast
reply was due to the rudeness contained in Facts

**Comment by jguille2** [comment]
Oh!
It was August, we were on vacation... and Snap4Arduino is a free and open source project... We are volunteers.

And also, you were talking about S4A... and I don't know if you were really talking about Snap4Arduino or about the old S4A (Scratch for Arduino). I forgot to answer this, sorry :(

And also, this is github. A place to share and contribute... You are free to use my work (or not)... and you can improve it freely. 

Bernat has shown you the "Zoom blocks" feature... But also, this is a web app... You can play it online and your browser configuration and screen resolution will do their work...
But you can change the browser zoom!!! That's all

Joan
