### ISSUE TITLE
Persistence without USB?

### ISSUE THREAD

**Issue by flumbo-byte** [bromagosa/Snap4Arduino#334]
How do you load code via S4A and keep the persistence after repowering the device?

**Comment by jguille2** [comment]
Hi @flumbo-byte

There is no persistence.

Snap4Arduino i a Snap! extension. All is living in your Snap side (the computer) and not in your boards.
All boards connected to Snap4Arduino have a Firmata firmware.
Then, you always need the Snap!/Snap4Arduino project open, this is controlling your connected boards

There is a transpiling feature ("new arduino translatable project") but it is only a "help" to build simple projects (obtaining the arduino ino code). It can't transpile any project.

For dynamic and also autonomous (with persistence) projects, we are using [Microblocks](https://microblocks.fun/).

Joan
