### ISSUE TITLE
Bluetooth port shows up in MacOSX but cannot be used

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/Snap4Arduino#36]
@maprzybylla wrote:

> if I try to connect to the BT-device attached to Arduino Uno (which as a user I'd assume is possible given the drop-dwon menu) I get this message: 
> Could not talk to Arduino in port /dev/cu.HC-06-DevB
> Check if firmata is loaded.
> 
> ![45999ba4-feaa-11e5-8932-255fe3d71857](https://cloud.githubusercontent.com/assets/1016697/14452995/6337c67e-0092-11e6-9aaf-c437c00d99d8.png)
> 
> And one more thing: if I then click ok and try to connect again, nothing happens :(

**Comment by bromagosa** [comment]
I'm pretty sure this one is fixed already, can someone with a MacOSX confirm it, please?

**Comment by tiagofer** [comment]
Hi, I'm using 1.1.6-beta-rc version on windows 10 and I have the same problems with you. I tested the FirmataPlus and StandardFirmata but do not work.

**Comment by hakanatas** [comment]
I have the same problem with MacOSX and also win10

**Comment by eglix** [comment]
Hi, i tried connect with standardfirmata and modified firmata(myself) but i did not get result.

**Comment by bromagosa** [comment]
Many users are successfully connecting Snap4Arduino over Bluetooth in MacOSX, Windows and GNU/Linux. I suspect there's something wrong in your particular setups...

Are you sure you're following [the instructions](https://github.com/bromagosa/Snap4Arduino/wiki/Autonomy-via-Blueetooth)?
