### ISSUE TITLE
Can Snap4Arduino pass 'real' parameters other than pinNumber when extending firmata? 

### ISSUE THREAD

**Issue by iszufu** [bromagosa/Snap4Arduino#38]
Here is the case: I hope to pass three parameters in double from s4a to a desktop robotic arm, but I am not sure if [this.arduino.board.sp.write(new Buffer([0xF0, ..., ..., 0xF7]))](http://blog.s4a.cat/2015/03/13/Extending-Firmata-for-Snap4Arduino.html) function can do this or not. I think it's more likely to be used for passing byte type data, like pin number.

**Comment by bromagosa** [comment]
Yes, of course! You can encode parameters of different types. Take in account that doubles, in Arduino, have the same precision as floats: https://www.arduino.cc/en/Reference/Double

Check out http://blog.s4a.cat/2015/03/24/LCD-Library-for-Snap4Arduino.html, and if you want a complex, full-featured Firmata extension example, check out @jguille2's [ImaginaFirmata](https://github.com/jguille2/SA5/blob/master/Sfiles/robolot16/ImaginaFirmata_0.5.ino) and its [Snap! module](https://raw.githubusercontent.com/jguille2/SA5/master/Sfiles/blocks_imagina.xml) counterpart.
