### ISSUE TITLE
what should be done to make the s4a support some basic functions of software serial?

### ISSUE THREAD

**Issue by edutec** [bromagosa/Snap4Arduino#4]
_From @Davis4Create on December 18, 2015 7:30_

I would like to modify the s4a to make it support the functions of software serial, so that more serial ports could be used when Arduino UNO being connected. Can anyone gives me some instructions to achieve this?
Here is a tutorial about expansion, but I don't really think this is enough, the work might be more complex.
http://blog.s4a.cat/2015/03/13/Extending-Firmata-for-Snap4Arduino.html

Give my high appreciation to someone who may help!

_Copied from original issue: edutec/Snap4Arduino-old-huge#70_

**Comment by fabianhemmert** [comment]
SoftwareSerial in S4A would be fantastic!
