### ISSUE TITLE
Snap4Arduino icon app shows nw.js standard icon

### ISSUE THREAD

**Issue by jguille2** [bromagosa/Snap4Arduino#41]
Hi,

Package.json defines `"icon": "s4a.ico"` but node supports only png/jpg formats.

We can use the existing _s4a_logo_sm.png_ file. Then, editing package.json with `"icon": "s4a_logo_sm.png"` it will show our icon.

Thanks

**Comment by bromagosa** [comment]
Thanks, Joan!

Will fix this today :)
