### ISSUE TITLE
Chrome App (experimental) download link error

### ISSUE THREAD

**Issue by jferran6** [bromagosa/Snap4Arduino#42]
Chrome App (experimental) download link in [http://s4a.cat/snap/]() is wrong.
Currently available at: [http://scaenaweb.citilab.eu/snap4arduino/]()

**Comment by bromagosa** [comment]
Sorry about that, I'm developing a browser plugin that will render the experimental Chrome version unnecessary, that's why I neglected it a little bit...

I'll hopefully have news about this by the end of this week, for now check out https://github.com/bromagosa/Snap4Arduino-plugin

**Comment by bromagosa** [comment]
Closed as this version is deprecated already, the proposed solution for Chromebook users is the Web-based version at http://github.com/bromagosa/Snap4Arduino-plugin
