### ISSUE TITLE
Network port connection option

### ISSUE THREAD

**Issue by jguille2** [bromagosa/Snap4Arduino#44]
Hi,
I know you're working in a network connection to the board.

Beyond the development of this functionality, I wondered about the appropriateness that always appear in the connection dialog.
Many people (and especially newcomers) work with a single board and may not have a great knowledge about computer ports. Then, direct connection (without asking a port) is a good implementation.

My suggestion: Add a menu item (a checkbox) to enable this 'network connection' function. Then, it will only appears in the connection dialog if it's enabled.

Thanks,

Joan

**Comment by bromagosa** [comment]
Good suggestion! I'll try to implement it today!
