### ISSUE TITLE
Bluetooth Connectivity

### ISSUE THREAD

**Issue by TheDiscovery** [bromagosa/Snap4Arduino#50]
Hi,

Just posting a quick question. I want to remotely program my Arduino UNO. Can I simply connect a bluetooth module via the Arduino's tx and rx pins, pair to the module and use Snap4Andruino with the appropriate COM port? Do I need to modify the Firmata sketch to exclude pins 1&2 from the digital inputs? Sorry for the newbie question.

**Comment by bromagosa** [comment]
Your first hunch is 100% correct, that's exactly what you need to do. No need to modify Firmata, but remember to set the BT module at the right speed for Firmata to communicate with the board (115200).

**Comment by edutec** [comment]
Watch out, the speed for Snap4Arduino is 57600!

Regards.

2016-06-15 9:06 GMT+02:00 Bernat Romagosa notifications@github.com:

> Your first hunch is 100% correct, that's exactly what you need to do. No
> need to modify Firmata, but remember to set the BT module at the right
> speed for Firmata to communicate with the board (115200).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/edutec/Snap4Arduino/issues/50#issuecomment-226105591,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFOy8RuBP0MeaVKo93y-nF2JQ9ksmZLSks5qL6SDgaJpZM4I2AUq
> .

## 

_José García_Coordinador àrea formació
+34 93 551 06 75 (ext.120)
jgarcia@citilab.eu

FUNDACIÓ PEL FOMENT DE LA

SOCIETAT DEL CONEIXEMENT

CORNELLÀ

Citilab Cornellà | http://citilab.eu | Pl. Can Suris s/n | 08940 Cornellà
de Llobregat | Barcelona

En compliment de la Llei Orgànica de Protecció de Dades de Caràcter
Personal (LOPD), l’informem que les seves dades de contacte han estat
incorporades en un fitxer titularitat de FUNDACIÓ PEL FOMENT DE LA SOCIETAT
DEL CONEIXEMENT (CITILAB). La finalitat d’aquest fitxer és la de mantenir
la relació amb els usuaris dels diferents oferts, inscripció als cursos i a
les activitats organitzades, facilitar la tramitació d’informació i
notificacions comercials i administratives, i en el cas de que vostè ho
hagi sol·licitat, l’enviament de publicitat relativa als serveis oferts.
FUNDACIÓ PEL FOMENT DE LA SOCIETAT DEL CONEIXEMENT (CITILAB) assegura la
confidencialitat de les dades aportades i garanteix que, en cap cas, seran
cedides per cap altre ús sense que hi hagi un consentiment previ i exprés
per part seva.

Per exercir els drets d’accés, rectificació, cancel·lació i oposició
previstos en la llei, pot adreçar-se mitjançant correu postal a FUNDACIÓ
PEL FOMENT DE LA SOCIETAT DEL CONEIXEMENT (CITILAB), Ref. Protecció de
Dades, Pl. Can Suris S/N, 08940, Cornellà de Llobregat, Barcelona, o bé
exercir els drets assenyalats mitjançant l’enviament de la seva petició al
correu electrònic avislegal@citilab.eu, indicant en l’assumpte del correu
“Ref. Protecció de Dades” (acreditant degudament la seva identitat).

**Comment by bromagosa** [comment]
Ouch! That's what I meant, sorry! :sweat_smile:
