### ISSUE TITLE
Expose the "Other" category

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/Snap4Arduino#51]

**Comment by jguille2** [comment]
I'm thinking about the category name...

New category blocks will not be imported to Snap!

Maybe a name like 'S4Ablocks' or 'S4A' would be fine.

Joan

**Comment by bromagosa** [comment]
We can just use `Other`, this is a "hidden" category that is already present in Snap!. Blocks added into `Other` will appear under this new category in Snap4Arduino, and in `Variables` in regular Snap!.
