### ISSUE TITLE
Premature leaving page dialog

### ISSUE THREAD

**Issue by stirlingstout** [bromagosa/Snap4Arduino#74]
Snap4Arduino! 0.1.5-beta

I've got a project which uses a Python server to implement a file server, so Snap! or Snap4Arduino can write/rread data (e.g., logged from an Arduino) to a file.

I've just been trying to implement a missing block (see the pictures) and when I try to Apply the change to the blocks in the first picture I get asked if I want to leave the page. If I take the call block out then Apply works OK. I've net yet confirmed if this happens in Snap!

![capture6](https://cloud.githubusercontent.com/assets/2162695/18853032/2ce7e73e-843b-11e6-8902-279e52e33329.png)

![capture1](https://cloud.githubusercontent.com/assets/2162695/18852952/b9536f82-843a-11e6-8e33-e4afe38dd43e.PNG)
![capture4](https://cloud.githubusercontent.com/assets/2162695/18852958/c237b1d0-843a-11e6-84b5-ec56fa8afd78.PNG)
![capture5](https://cloud.githubusercontent.com/assets/2162695/18852959/c23e2e5c-843a-11e6-939d-69806d164f72.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2162695/18852960/c24528c4-843a-11e6-91d7-40be28cc34c6.PNG)

**Comment by bromagosa** [comment]
Hi John!

Obvious question (sorry), have you tried using the latest Snap4Arduino version?

I assume you're using the desktop flavor, right? If that's the fact, you could actually implement file system operations without the need of an intermediary server, here's an example:

![image](https://cloud.githubusercontent.com/assets/1016697/18862527/007bf210-848d-11e6-8cf7-ee86bc26d829.png)

Still, I'm not sure what can be causing the leave page dialog to show up. Can you attach the project XML here so I can take a look?

Thanks! :)

**Comment by stirlingstout** [comment]
Bernat

I’d just downloaded the version that I thought was the latest from the site (1.0.6 Beta). I haven’t tried it with the web version yet.

I didn’t know about the require(‘fs’) technique, which is great, but I wanted a solution for ‘normal’ Snap! to run in the browser.

I’ll have another go at reproducing the problem and  send you the project XML.

John

**Comment by jguille2** [comment]
Last version is 1.1.6 beta-rc3 released on 19/08/2016.

Current site is http://snap4arduino.org/

**Comment by stirlingstout** [comment]
The version I'm running I downloaded from the site http://snap4arduino.org/ yesterday, using the Microsoft Windows (64 bits) link, but clicking on the logo when running Snap4Arduino and  selecting About Snap4Arduino... shows 0.1.5-beta.

John

**Comment by bromagosa** [comment]
Ouch! That's my fault! Thanks for reporting this!

**Comment by stirlingstout** [comment]
?Oh, and the title bar shows Snap4Arduino 1.0.6-beta.

John

**Comment by stirlingstout** [comment]
Bernat

Does that mean you can reproduce the problem? Or have found the solution? If so I won't send you the xml.

John

**Comment by bromagosa** [comment]
Nope, that just means I messed up the version reporting in the About dialog, but I still need the XML to test what's going on with your project :)

**Comment by stirlingstout** [comment]
Here's the project. If I edit the block called **(table from file called (filename))** I can Apply it as it currently, but if I drag the **map** block that's on the scripting area into the **[report []]** and do Apply I get asked if I want to leave the page.

I've put my SnapFiles on Github at stirlingstout/SnapFiles. So far it works really nicely with an Arduino and Snap4Arduino, but it would be nice to have the tables feature from the current Snap! (and keyboard editing) to display data logging files.  

[PrematureLeavingPage.zip](https://github.com/edutec/Snap4Arduino/files/495287/PrematureLeavingPage.zip)

**Comment by bromagosa** [comment]
Hmm... I see, it does work in my PC on the latest dev version. Can you try with the version I'm linking?

http://snap4arduino.org/downloads/test/linux32.zip
http://snap4arduino.org/downloads/test/linux64.zip
http://snap4arduino.org/downloads/test/osx64.zip
http://snap4arduino.org/downloads/test/win32.zip
http://snap4arduino.org/downloads/test/win64.zip

**Comment by stirlingstout** [comment]
I tried the Win64 version and that doesn't give the error, but when I import the project it tells me it was made with a different version of Snap!

**Comment by bromagosa** [comment]
Yep, that's a known issue I'll resolve before publishing the next release.

So it seems it's fixed in my dev branch, I'll close this issue when I release it :)

Thanks for your patience!

**Comment by stirlingstout** [comment]
Fantastic: table support and keyboard editing are in the beta version you pointed me to!

**Comment by bromagosa** [comment]
yep :)

I'm just waiting to fix an annoying bug to publish it, we'll hopefully fix it tomorrow with @jguille2...

**Comment by bromagosa** [comment]
About to release 1.2, so I'm closing this.
