### ISSUE TITLE
Can't send project to the board (arduino)

### ISSUE THREAD

**Issue by cop663** [bromagosa/Snap4Arduino#81]
I am using arduino nano,

see the pic attached
![111](https://cloud.githubusercontent.com/assets/2016579/19149164/11784e66-8bf3-11e6-88a0-697d4174dfcc.jpg)

then

![222](https://cloud.githubusercontent.com/assets/2016579/19149199/3d3f6c14-8bf3-11e6-9adb-49ef09e0f793.jpg)

Anyone know what happens?

Thank you

**Comment by bromagosa** [comment]
This feature is for Linino-capable boards, such as the Yun, Yun mini, Tian or Industrial 101. The rest of the boards cannot run the Snap! environment inside, as they have very limited RAM.

**Comment by cop663** [comment]
Thank you!

**Comment by bromagosa** [comment]
(you can however transpile simple scripts into Arduino sketches, check this out: http://blog.s4a.cat/2015/06/09/Snap4Arduino-Arduino-sketch-generation.html)
