### ISSUE TITLE
[ChromeOS] Custom JS block throws error

### ISSUE THREAD

**Issue by bromagosa** [bromagosa/Snap4Arduino#85]
![image](https://cloud.githubusercontent.com/assets/1016697/19264820/ad085d1e-8fa2-11e6-819b-b6a881332005.png)

**Comment by bromagosa** [comment]
Not doable. Google [doesn't want users to have the power to execute code in their own machines](https://developer.chrome.com/apps/contentSecurityPolicy#what).The solution is to use the Web version instead, and document that JS blocks cannot be used in the Chromebook version.

How sad is that?

**Comment by jguille2** [comment]
So sad :(
