### ISSUE TITLE
Second sprite asks for arduino connection

### ISSUE THREAD

**Issue by microspace** [bromagosa/Snap4Arduino#89]
When I add second stripe and try to access some ports of Arduino, it asks for connection to board. But I'm already connected to board from the firstt sprite. Is it standard behaviour?

**Comment by jguille2** [comment]
Yes!
One board to one sprite.
You can connect many boards to a project... and every board will be managed for one sprite.

Then, if you are in a 'non connected sprite' and you want to do a 'board action', you must ask this action to the 'board sprite' (broadcast --> when I receive).

That's all,

Joan

**Comment by microspace** [comment]
Ah, I see. Thank you!
