### ISSUE TITLE
Implement "map" function

### ISSUE THREAD

**Issue by microspace** [bromagosa/Snap4Arduino#93]
I want to control crosshair with couple of potentiometers. X, Y dimensions of screen are -180,+180. ADC gives me 0..1023 range. It will be very handy if there were "map" function, same as in Arduino C.

**Comment by bromagosa** [comment]
It is actually a good and simple arithmetic exercise to implement this one yourself:

![image](https://cloud.githubusercontent.com/assets/1016697/19645419/e8878bc4-99f4-11e6-895e-d1b65f9bb510.png)

![image](https://cloud.githubusercontent.com/assets/1016697/19645421/effc0358-99f4-11e6-8994-43893f251e1e.png)

Here's the block in case you want to import it into your projects: 
[map.zip](https://github.com/bromagosa/Snap4Arduino/files/547725/map.zip).

By the way, `map` is not the best name for this block, as in languages with higher order functions like Snap<i>!</i>, `map` usually refers to [something else](https://en.wikipedia.org/wiki/Map_%28higher-order_function%29).

**Comment by microspace** [comment]
Thank you. Is there a way to make this function avaliable at startup?

**Comment by bromagosa** [comment]
Well, not at the moment... but it's just a drag and drop away :)
