### ISSUE TITLE
Blinking goes out of sync

### ISSUE THREAD

**Issue by microspace** [bromagosa/Snap4Arduino#94]
I've attached 3 led to 9, 11 and 13 pin. 
![image](https://cloud.githubusercontent.com/assets/2958584/19652611/d496b6f4-9a2a-11e6-8a3c-d5214c21c763.png)

After several minutes of synchronuous blinking, the 11th pin led start to blink out of sync with others.
Is it firmata issue?

**Comment by bromagosa** [comment]
Hi @microspace.

I'll set up the same test today and let it run to see if it fails on me. This is actually a test I used to leave running overnight to confirm things worked as expected and it used to work fine.

Can you tell me more about your setup? What Snap4Arduino flavor are you using (GNU/Linux [32/64], Win [32/64], ChromeOS, Web?), and what kind of board?

Thanks! :)

**Comment by microspace** [comment]
Original Arduino UNO, Windows 10 64.
But...
I can't reproduce the bug now.
I'm really sorry
