### ISSUE TITLE
Error while save project 

### ISSUE THREAD

**Issue by aguscout** [bromagosa/Snap4Arduino#96]
snap4arduino present problem save project, no present action button browser , my version is 1.2

**Comment by jguille2** [comment]
Which is your OS ?
I'm testing in Linux and Save function is ok
![s4a_save](https://cloud.githubusercontent.com/assets/2926315/19841996/372de6a0-9f14-11e6-9b57-66d47a879632.png)

**Comment by aguscout** [comment]
my SO is Windows, when press button the Browser no open   tree directory

**Comment by bromagosa** [comment]
Please see page 14 of the Snap<i>!</i> manual about how to save projects: https://snap.berkeley.edu/SnapManual.pdf

Browser doesn't refer to "File Browser", but to an internal storage system for Snap. Just give the project a name and click Save, and it'll stay there.

Cheers,
Bernat.

**Comment by aguscout** [comment]
do you plan  saved projects to disk  in next versions or not ?

**Comment by bromagosa** [comment]
Please check the manual, you can export projects to disk.

**Comment by aguscout** [comment]
ok,  thanks
