### ISSUE TITLE
adding new devices

### ISSUE THREAD

**Issue by najiJazzar** [bromagosa/Snap4Arduino#99]
As I was following this link  [http://blog.s4a.cat/2015/03/13/Extending-Firmata-for-Snap4Arduino.html](url).

I tried to add my own ultrasonic sensor block, which has two pins (trig,echo)unlike the one listed in the website : [http://blog.s4a.cat/2015/03/31/Ultrasound-Library-for-Snap4Arduino.html](url) which only have 1 pin.

I found that there are some javascript functions in the one you created (shown on pictures attached) that was not illustrated.
So please if you could give some hints or few steps to do in order to understand the logic of the javascript code. just some tips and I'll spend the time to read and understand.

![selection_002](https://cloud.githubusercontent.com/assets/21219988/19968004/499c1b1c-a1db-11e6-8b5a-6e22e23b9c96.png)
![selection_003](https://cloud.githubusercontent.com/assets/21219988/19968003/499a85ae-a1db-11e6-8495-4e76b085007f.png)

**Comment by jguille2** [comment]
Hi,
If you want to use that project, you must also change arduino sketch.

You can use [this other](https://github.com/jguille2/SA5/blob/master/firmata/SA5Firmata.md), that have an Ultrasonic block with two pins (you can also use this with only one pin (the same in two slots)).

To understand the logic of this, you must look at block code (javascript) and arduino code. We use the SYSEX commands in the Arduino sketch to define new functions.

Joan

**Comment by najiJazzar** [comment]
I've uploaded SA5Firmata2.ino to my Arduino mega, and tried the ping reporter for HC-SR04 ultrasonic sensor and the result was as shown in the picture.
_Inside:Error:
Please upload SA5Firmata2.ino a higher version_
Any ideas !!

![tojoan](https://cloud.githubusercontent.com/assets/21219988/20037860/6c388c66-a431-11e6-979d-dceea53c13c4.png)
